---
apiVersion: v1
kind: Namespace
metadata:
  name: test-prod
  labels:
    app : test
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-qa
  labels:
    app : test
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-dev
  labels:
    app : test
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-build
  labels:
    app : test
